export class AudioSystem{
  constructor(settings){this.settings=settings;this.ctx=null;this.musicGain=null;this.sfxGain=null;this.timer=0;this.step=0}
  init(){if(this.ctx)return;const C=window.AudioContext||window.webkitAudioContext;if(!C)return;this.ctx=new C();this.musicGain=this.ctx.createGain();this.sfxGain=this.ctx.createGain();this.musicGain.connect(this.ctx.destination);this.sfxGain.connect(this.ctx.destination);this.applySettings()}
  applySettings(){if(!this.ctx)return;this.musicGain.gain.value=this.settings.music;this.sfxGain.gain.value=this.settings.sfx}
  wake(){this.init();this.ctx?.resume()}
  tone(a,b=.12,type='square',gain=.08){this.wake();if(!this.ctx||!this.settings.sfx)return;const n=this.ctx.currentTime,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.setValueAtTime(a,n);o.frequency.exponentialRampToValueAtTime(Math.max(35,a*.72),n+b);g.gain.setValueAtTime(gain,n);g.gain.exponentialRampToValueAtTime(.0001,n+b);o.connect(g);g.connect(this.sfxGain);o.start(n);o.stop(n+b+.02)}
  play(name){const sounds={jump:[420,.15,'square',.07],coin:[940,.1,'square',.06],hurt:[120,.28,'sawtooth',.12],shoot:[650,.08,'square',.05],stomp:[180,.12,'triangle',.09],win:[720,.4,'triangle',.1],boss:[72,.7,'sawtooth',.12],buy:[1100,.16,'sine',.08]};if(sounds[name])this.tone(...sounds[name])}
  startMusic(dimension=0,boss=false){this.stopMusic();this.wake();if(!this.ctx||!this.settings.music)return;const scales=[[262,330,392,523],[220,277,330,440],[294,370,440,587],[247,330,392,494],[196,247,294,392],[330,415,494,659],[185,233,277,370],[147,220,294,440],[165,196,247,330],[131,196,262,392]];const notes=scales[dimension];this.step=0;const tick=()=>{if(!this.timer)return;const note=notes[this.step%4]*(boss&&this.step%8>4?.5:1);const n=this.ctx.currentTime,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=dimension>4?'sawtooth':'square';o.frequency.value=note;g.gain.setValueAtTime(.032,n);g.gain.exponentialRampToValueAtTime(.0001,n+.16);o.connect(g);g.connect(this.musicGain);o.start(n);o.stop(n+.18);this.step++;this.timer=setTimeout(tick,boss?210:260)};this.timer=1;tick()}
  stopMusic(){if(this.timer)clearTimeout(this.timer);this.timer=0}
}
